#!/usr/bin/env node
/* ============================================================
   Derive the design system's token files from styles.css.
   ------------------------------------------------------------
   The site's stylesheet is the source of truth for Khayt's colour, type and
   spacing — it carries the reasoning for each value in comments, and it is
   what the live site actually renders from. This script reads the custom
   properties out of it rather than keeping a second copy, so the design
   system cannot drift from the site the way a hand-maintained duplicate
   would. Re-run it whenever styles.css changes:

     node .design-sync/extract-tokens.mjs

   It writes design-system/styles/*.css, which are generated files.
   ============================================================ */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');   // the website repo root
const PKG = path.join(import.meta.dirname, 'package');  // the converter-only DS package
const css = fs.readFileSync(path.join(ROOT, 'styles.css'), 'utf8');

// Pull one selector's declaration block, comments and all.
function block(selector) {
  const start = css.indexOf(selector + ' {');
  if (start === -1) throw new Error(`could not find "${selector}" in styles.css`);
  const open = css.indexOf('{', start);
  const end = css.indexOf('\n}', open);
  if (end === -1) throw new Error(`could not find the end of "${selector}"`);
  return css.slice(open + 1, end).replace(/^\n/, '');
}

// Only the custom properties: the deep block also carries background/color,
// which belong to the page, not to the token set.
function customPropsOnly(body) {
  return body
    .split('\n')
    .filter(l => !/^\s*(background|color)\s*:/.test(l))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd();
}

const FONTS_IMPORT = `/* Generated by .design-sync/extract-tokens.mjs — do not edit.
   Khayt loads these from Google Fonts with a <link> in every page's <head>.
   The design system states the same families as a remote @import so anything
   rendered from these tokens resolves the real faces at runtime. */
@import url('https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800;900&family=Hanken+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=Almarai:wght@700;800&display=swap');
`;

const header = name => `/* Generated by .design-sync/extract-tokens.mjs from styles.css — do not edit.
   ${name} */\n`;

const out = path.join(PKG, 'styles');
fs.mkdirSync(out, { recursive: true });

/* One flat stylesheet, not a file of @imports.
   The converter treats cfg.cssEntry as the design system's compiled CSS and
   copies it to the bundle root as _ds_bundle.css. An @import-only file breaks
   there (its relative paths no longer resolve) and is rejected as a stub, so
   the tokens are concatenated in load order instead. The remote font @import
   has to lead: CSS requires @import before any rule. */
const flat = [
  `/* Generated by .design-sync/extract-tokens.mjs from styles.css — do not edit.
   Khayt's design foundations: colour, type and spacing, straight from the
   stylesheet the live site renders from. Re-run the script after changing
   styles.css. */`,
  FONTS_IMPORT,
  `/* ---- Khayt on paper: the default surface the site is written on. ---- */`,
  ':root {\n' + block(':root') + '\n}',
  `/* ---- The deep treatment: the same token NAMES re-pointed onto navy.
   Applied by putting class="deep" on <body> — services.html is the one page
   that does. Anything reading these tokens flips with it, which is why the
   site's cards, tables and buttons needed no dark variants of their own. ---- */`,
  'body.deep {\n' + customPropsOnly(block('body.deep')) + '\n}',
].join('\n\n') + '\n';

fs.writeFileSync(path.join(out, 'khayt.css'), flat);

// The split files are gone: one flat sheet is what the converter consumes.
for (const stale of ['fonts.css', 'tokens.css', 'tokens-deep.css']) {
  const f = path.join(out, stale);
  if (fs.existsSync(f)) fs.rmSync(f);
}

const props = (flat.match(/^\s*--[a-z0-9-]+\s*:/gm) || []).length;
console.log('.design-sync/package/styles/khayt.css —', props, 'custom properties,', flat.length, 'bytes');
